# Generated by Django 5.2.10 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_food_discount_percentage_hotel_image_hotel_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg'), ('biryani', 'Biryani'), ('dessert', 'Dessert'), ('snack', 'Snack')], default='veg', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity_left',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.2, max_digits=2),
        ),
    ]
